# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-26 18:13
from __future__ import unicode_literals

from django.db import migrations
from django.db import models

import kolibri.core.device.models
import kolibri.core.fields
import kolibri.core.utils.validators
from kolibri.utils.conf import OPTIONS


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0016_osuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicesettings",
            name="extra_settings",
            field=kolibri.core.fields.JSONField(
                default={
                    "allow_download_on_mettered_connection": False,
                    "allow_learner_download_resources": False,
                    "enable_automatic_download": True,
                    "limit_for_autodownload": 0,
                    "primary_storage_connection": "/home/jose/.kolibri/content",
                    "secondary_storage_connections": [],
                    "set_limit_for_autodownload": False,
                },
                validators=[
                    kolibri.core.utils.validators.JSON_Schema_Validator(
                        {
                            "additionalProperties": False,
                            "properties": {
                                "allow_download_on_mettered_connection": {
                                    "type": "boolean"
                                },
                                "allow_learner_download_resources": {"type": "boolean"},
                                "enable_automatic_download": {"type": "boolean"},
                                "limit_for_autodownload": {"type": "integer"},
                                "primary_storage_connection": {"type": "string"},
                                "secondary_storage_connections": {
                                    "items": {"type": "string"},
                                    "type": "array",
                                },
                                "set_limit_for_autodownload": {"type": "boolean"},
                            },
                            "type": "object",
                        }
                    )
                ],
            ),
        ),
    ]
